"""created_on

Revision ID: 1dbab0a7eab0
Revises: 43d30bd866d9
Create Date: 2024-01-03 12:19:37.485225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1dbab0a7eab0'
down_revision: Union[str, None] = '43d30bd866d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('users', 'updated_on')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_on', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True))
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
